### ISSUE TITLE
Broken dependency - gensim 

### ISSUE THREAD

**Issue by vwbusguy** [UCSB-PSTAT/comm-594ct-container-image#1]
Image builds but fails to import gensim on scipy.

```
+ podman run -it --rm --pull=never localhost/comm-594ct python -c 'import afinn; import datasets; import gensim; import jax; import keras; import matplotlib; import nltk; import numpy; import pandas; import praw; import pyjq; import pyLDAvis; from pytensor import tensor as pt; import scipy; import scrapy; import seaborn; import selenium; import sklearn; import statsmodels; import sympy; import tensorflow; import tokenizers; import top2vec; import torch; import transformers; import wordcloud; import yellowbrick; import zstandard'
time="2024-12-23T23:20:08Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
Entered start.sh with args: python -c import afinn; import datasets; import gensim; import jax; import keras; import matplotlib; import nltk; import numpy; import pandas; import praw; import pyjq; import pyLDAvis; from pytensor import tensor as pt; import scipy; import scrapy; import seaborn; import selenium; import sklearn; import statsmodels; import sympy; import tensorflow; import tokenizers; import top2vec; import torch; import transformers; import wordcloud; import yellowbrick; import zstandard
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: python -c import afinn; import datasets; import gensim; import jax; import keras; import matplotlib; import nltk; import numpy; import pandas; import praw; import pyjq; import pyLDAvis; from pytensor import tensor as pt; import scipy; import scrapy; import seaborn; import selenium; import sklearn; import statsmodels; import sympy; import tensorflow; import tokenizers; import top2vec; import torch; import transformers; import wordcloud; import yellowbrick; import zstandard
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.12/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/gensim/corpora/indexedcorpus.py", line 14, in <module>
    from gensim import interfaces, utils
  File "/opt/conda/lib/python3.12/site-packages/gensim/interfaces.py", line 19, in <module>
    from gensim import utils, matutils
  File "/opt/conda/lib/python3.12/site-packages/gensim/matutils.py", line 20, in <module>
    from scipy.linalg import get_blas_funcs, triu
ImportError: cannot import name 'triu' from 'scipy.linalg' (/opt/conda/lib/python3.12/site-packages/scipy/linalg/__init__.py)
```

Seems the same issue as https://github.com/UCSB-PSTAT/ling-research-container-image/issues/6

**Comment by ParadoxGuitarist** [comment]
https://github.com/piskvorky/gensim/pull/3524/files
